name: planetwalker
favicon: null
layout_spectrum: 0.32622
typography_spectrum: 0.13407
title: 'Walking the Planet, One Step at a Time'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d5fbfe'
    - '#173456'
    - '#88d1f4'
    - '#89a1ab'
    - '#3b6891'
  brandStrength: 0.6875
  lightness: 0.5
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
